[project]
name = "libelium-parking-sensor-v2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "incremental>=24.11.0",
    "pydantic>=2.12.5",
]
